name: Github Actions로 테스트 자동화하기
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 불러오기
        uses: actions/checkout@v5

      - name: Node.js 설치하기
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'

      - name: 의존성(라이브러리) 설치
        run: npm ci

      - name: 테스트 실행하기
        run: npm run test