# 이름 짓기
name: Github Actions 연습하기
# 언제 이 작업을 실행할지 정의
# push: github에 push할 때마다 실행
on: push

# jobs: 어떤 작업을 할지
jobs:
  push-job:
    # runs-on: 어떤 OS에서 실행할지
    runs-on: ubuntu-latest
    # steps: 각 단계에서 실행할 명령 / 액션
    steps:
      - name: 첫 번째 작업
        run: echo "첫 번째 작업 실행 중"

      - name: 여러 명령어 문장 작성하기
        run: |
          echo "첫 번째 명령어"
          echo "두 번째 명령어"

      - name: Github Actions 자체에 저장되어 있는 변수 사용해보기
        run: |
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY

      - name: Github Actions Secret 변수 사용해보기
        run: |
          echo ${{ secrets.MY_NAME }}
          echo ${{ secrets.BBB }}
